import { useRouter } from "next/router";

import Head from "next/head";
import TitleBar from "@/components/organisms/TitleBar";
import Header from "@/components/organisms/Header";
import Border from "@/components/atoms/Border";
import TimeFilters from "@/components/molecules/PostLoop/TimeFilters";
import PostLoop from "@/components/organisms/PostLoop/PostLoop";
import JobLoop from "@/components/organisms/RemoteJobs/JobLoop";
import PartnerUpLoop from "@/components/organisms/PartnerUp/PartnerUpLoop";
import MeetupsLoop from "@/components/organisms/Meetups/MeetupsLoop";
import Footer from "@/components/organisms/Footer/Footer";

import {
  posts,
  jobInfo,
  partnerInfo,
  meetupInfo,
  footerColumns,
} from "utils/consts";
import Container from "@/components/templates/Container";
export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TitleBar />
        <Container className="space-y-9">
          <section>
            <div className="mt-9">
              <Header />
            </div>
            <Border className="my-3" />

            <TimeFilters />
            <Border className="my-3" />
            <PostLoop props={posts} />
          </section>
          <section>
            <JobLoop props={jobInfo} />
          </section>
          <section>
            <PartnerUpLoop props={partnerInfo} />
          </section>
          <section>
            <MeetupsLoop props={meetupInfo} />
          </section>
        </Container>
      </main>
      <Container className="my-12">
        <footer>
          <Footer props={footerColumns} router={router}></Footer>
        </footer>
      </Container>
    </div>
  );
}
